apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cat-app
  labels:
    app.kubernetes.io/part-of: tanzu-cat-app
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: cat-app
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-cat-app
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: cat-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
        image: devworkspaceacr.azurecr.io/samples/cat-app-flux-system@sha256:d032a22b873e690c37dab3244d79d7db35b34d3e187cb3e3d1a42c719fe7f623
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

