apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cat-app
  labels:
    app.kubernetes.io/part-of: tanzu-cat-app
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: cat-app
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-cat-app
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: cat-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
        image: devworkspaceacr.azurecr.io/samples/cat-app-flux-system@sha256:f6b43bc15d68ed26dd08cc455d7e2ce7f47a77846381e8ec4112c3a860e9061a
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

