apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cat-app
  labels:
    app.kubernetes.io/part-of: tanzu-cat-app
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: cat-app
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: ""
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-cat-app
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: cat-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
        image: devworkspaceacr.azurecr.io/samples/cat-app-flux-system@sha256:b8399bed9d00ddeb7a83e147655ac56326dabb1a2c0877e92f764bb478552539
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

